<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup Condition="'$(OS)' == 'OSX'">
    <!-- Required by the VS Code debugger on macOS  -->
    <None Include="/opt/homebrew/lib/libSDL2.dylib" CopyToOutputDirectory="PreserveNewest" />
    <None Include="/opt/homebrew/lib/libSDL2_image.dylib" CopyToOutputDirectory="PreserveNewest" />
    <None Include="/opt/homebrew/lib/libSDL2_ttf.dylib" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>


</Project>
