<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <UserProfile Condition="'$(OS)' == 'Windows_NT'">$(USERPROFILE)</UserProfile>
    <ScoopPath Condition="'$(OS)' == 'Windows_NT'">$(UserProfile)\scoop\apps</ScoopPath>
    <HomebrewPath Condition="'$(OS)' != 'Windows_NT'">/opt/homebrew/lib</HomebrewPath>
  </PropertyGroup>

  <ItemGroup Condition="'$(OS)' == 'Windows_NT'">
    <None Include="$(ScoopPath)\sdl2\current\lib\SDL2.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(ScoopPath)\sdl2-image\current\lib\SDL2_image.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(ScoopPath)\sdl2-ttf\current\lib\SDL2_ttf.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup Condition="'$(OS)' != 'Windows_NT'">
    <None Include="$(HomebrewPath)/libSDL2.dylib" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(HomebrewPath)/libSDL2_image.dylib" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(HomebrewPath)/libSDL2_ttf.dylib" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>

